"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-07-23 11:33:12.718376
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel column types (AutoString) appear in this autogenerated migration

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('current_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name', 'job_title', 'platform', 'applied_date', name='uq_application_identity')
    )
    op.create_table('companyprofile',
    sa.Column('company_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headquarters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recent_news', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_urls_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('researched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_key')
    )
    op.create_table('pipelinerun',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('emails_fetched', sa.Integer(), nullable=False),
    sa.Column('emails_relevant', sa.Integer(), nullable=False),
    sa.Column('applications_created', sa.Integer(), nullable=False),
    sa.Column('events_created', sa.Integer(), nullable=False),
    sa.Column('errors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emails_total', sa.Integer(), nullable=True),
    sa.Column('emails_scrutinized', sa.Integer(), nullable=False),
    sa.Column('emails_extracted', sa.Integer(), nullable=False),
    sa.Column('emails_written', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('suggestions_created', sa.Integer(), nullable=False),
    sa.Column('run_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processedemail',
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pipeline_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('reviewsuggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggested_classification', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_extract_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('suggested_extract_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statusevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('source_email_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_extract_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statusevent')
    op.drop_table('reviewsuggestion')
    op.drop_table('processedemail')
    op.drop_table('pipelinerun')
    op.drop_table('companyprofile')
    op.drop_table('application')
    # ### end Alembic commands ###
